-- Generated by tools/strategic_icon_config.sh. Edit icon targets in that file,
-- not here or in mod_icons.lua.

UnitIconAssignments = {}

local RecipeIconRules = {
-- BEGIN GENERATED ICON RULES
    {
        name = "pgen",
        techs = { [2] = true, [3] = true, },
        categories = { "STRUCTURE", "ENERGYPRODUCTION", },
        strategicIconNames = { },
        excludedBlueprints = { },
    },
    {
        name = "mex",
        techs = { [1] = true, [2] = true, [3] = true, },
        categories = { "STRUCTURE", "MASSEXTRACTION", },
        strategicIconNames = { },
        excludedBlueprints = { },
    },
    {
        name = "intel",
        techs = { [1] = true, [2] = true, [3] = true, },
        categories = { },
        strategicIconNames = { "icon_structure1_intel", "icon_structure2_intel", "icon_structure3_intel", },
        excludedBlueprints = { },
    },
    {
        name = "tml",
        techs = { [2] = true, },
        categories = { },
        strategicIconNames = { "icon_structure2_missile", },
        excludedBlueprints = { },
    },
    {
        name = "sml",
        techs = { [3] = true, },
        categories = { },
        strategicIconNames = { "icon_structure3_missile", },
        excludedBlueprints = { },
    },
    {
        name = "artillery",
        techs = { [3] = true, },
        categories = { "STRUCTURE", "ARTILLERY", },
        strategicIconNames = { },
        excludedBlueprints = { "xab2307", },
    },
    {
        name = "smd",
        techs = { [3] = true, },
        categories = { "STRUCTURE", "ANTIMISSILE", },
        strategicIconNames = { },
        excludedBlueprints = { },
    },
-- END GENERATED ICON RULES
}

local function HasCategory(bp, wanted)
    if not bp.Categories then
        return false
    end

    for _, category in ipairs(bp.Categories) do
        if category == wanted then
            return true
        end
    end

    return false
end

local function Contains(values, wanted)
    for _, value in ipairs(values) do
        if value == wanted then
            return true
        end
    end

    return false
end

local function GetTech(bp)
    if HasCategory(bp, "EXPERIMENTAL") then
        return 4
    elseif HasCategory(bp, "TECH3") then
        return 3
    elseif HasCategory(bp, "TECH2") then
        return 2
    end

    return 1
end

local function MatchesRecipe(rule, id, bp, tech)
    if not rule.techs[tech] then
        return false
    end

    if Contains(rule.excludedBlueprints, string.lower(id)) then
        return false
    end

    for _, category in ipairs(rule.categories) do
        if not HasCategory(bp, category) then
            return false
        end
    end

    if table.getn(rule.strategicIconNames) > 0
        and not Contains(rule.strategicIconNames, bp.StrategicIconName)
    then
        return false
    end

    return true
end

function ScriptedIconAssignments(units, projectiles, icons)
    local assignments = {}
    local availableIconSets = {}

    for _, path in ipairs(icons or {}) do
        local filename = string.match(path, "([^/]+)$") or path
        if string.sub(filename, -9) == "_rest.dds" then
            availableIconSets[string.sub(filename, 1, -10)] = true
        end
    end

    for id, bp in pairs(units) do
        local iconSet
        local tech = GetTech(bp)

        for _, rule in ipairs(RecipeIconRules) do
            if MatchesRecipe(rule, id, bp, tech) then
                local candidate = "nextui_" .. rule.name .. tech
                if availableIconSets[candidate] then
                    iconSet = candidate
                    break
                end
            end
        end

        -- Every native numbered icon has an automatically generated variant
        -- with the configured global tech marker. Explicit recipes above keep
        -- priority over this fallback.
        if not iconSet and bp.StrategicIconName then
            local nativeIconSet = string.match(
                bp.StrategicIconName,
                "([^/]+)$"
            ) or bp.StrategicIconName
            local candidate

            if tech == 4 then
                candidate = "nextui_tech4_" .. nativeIconSet
            else
                candidate = "nextui_tech_" .. nativeIconSet

                -- Some blueprints use an unnumbered native set despite having
                -- a normal tech category. Prefer its numbered counterpart when
                -- FAF provides one.
                if not availableIconSets[candidate] then
                    local family, role = string.match(
                        nativeIconSet,
                        "^(icon_[a-z]+)_(.+)$"
                    )
                    if family and role then
                        candidate = "nextui_tech_"
                            .. family .. tech .. "_" .. role
                    end
                end

                if not availableIconSets[candidate] then
                    candidate = "nextui_tech"
                        .. tech .. "_" .. nativeIconSet
                end
            end

            if availableIconSets[candidate] then
                iconSet = candidate
            end
        end

        if iconSet then
            assignments[id] = {
                BlueprintId = id,
                IconSet = iconSet,
            }
        end
    end

    return assignments
end
